apiVersion: v1
kind: ReplicationController
metadata:
  name: distkeras-rc-master
spec:
  replicas: 1
  selector:
    app: distkeras-master
  template:
    metadata:
      labels:
        app: distkeras-master
    spec:
      nodeSelector:
        type: master
      containers:
        - name: distkeras-master
          image: distkeras_master_kube:1.0
          ports:
            - containerPort: 8888
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 4040
            - containerPort: 7001
            - containerPort: 7002
            - containerPort: 7003
            - containerPort: 7004
            - containerPort: 7005
            - containerPort: 7006
